// <auto-generated />
namespace CollegeApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tt10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tt10));
        
        string IMigrationMetadata.Id
        {
            get { return "202205180647425_tt10"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
